require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe BctLettersController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # BctLetter. As you add validations to BctLetter, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BctLettersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all bct_letters as @bct_letters" do
      bct_letter = BctLetter.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:bct_letters)).to eq([bct_letter])
    end
  end

  describe "GET #show" do
    it "assigns the requested bct_letter as @bct_letter" do
      bct_letter = BctLetter.create! valid_attributes
      get :show, {:id => bct_letter.to_param}, valid_session
      expect(assigns(:bct_letter)).to eq(bct_letter)
    end
  end

  describe "GET #new" do
    it "assigns a new bct_letter as @bct_letter" do
      get :new, {}, valid_session
      expect(assigns(:bct_letter)).to be_a_new(BctLetter)
    end
  end

  describe "GET #edit" do
    it "assigns the requested bct_letter as @bct_letter" do
      bct_letter = BctLetter.create! valid_attributes
      get :edit, {:id => bct_letter.to_param}, valid_session
      expect(assigns(:bct_letter)).to eq(bct_letter)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new BctLetter" do
        expect {
          post :create, {:bct_letter => valid_attributes}, valid_session
        }.to change(BctLetter, :count).by(1)
      end

      it "assigns a newly created bct_letter as @bct_letter" do
        post :create, {:bct_letter => valid_attributes}, valid_session
        expect(assigns(:bct_letter)).to be_a(BctLetter)
        expect(assigns(:bct_letter)).to be_persisted
      end

      it "redirects to the created bct_letter" do
        post :create, {:bct_letter => valid_attributes}, valid_session
        expect(response).to redirect_to(BctLetter.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved bct_letter as @bct_letter" do
        post :create, {:bct_letter => invalid_attributes}, valid_session
        expect(assigns(:bct_letter)).to be_a_new(BctLetter)
      end

      it "re-renders the 'new' template" do
        post :create, {:bct_letter => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested bct_letter" do
        bct_letter = BctLetter.create! valid_attributes
        put :update, {:id => bct_letter.to_param, :bct_letter => new_attributes}, valid_session
        bct_letter.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested bct_letter as @bct_letter" do
        bct_letter = BctLetter.create! valid_attributes
        put :update, {:id => bct_letter.to_param, :bct_letter => valid_attributes}, valid_session
        expect(assigns(:bct_letter)).to eq(bct_letter)
      end

      it "redirects to the bct_letter" do
        bct_letter = BctLetter.create! valid_attributes
        put :update, {:id => bct_letter.to_param, :bct_letter => valid_attributes}, valid_session
        expect(response).to redirect_to(bct_letter)
      end
    end

    context "with invalid params" do
      it "assigns the bct_letter as @bct_letter" do
        bct_letter = BctLetter.create! valid_attributes
        put :update, {:id => bct_letter.to_param, :bct_letter => invalid_attributes}, valid_session
        expect(assigns(:bct_letter)).to eq(bct_letter)
      end

      it "re-renders the 'edit' template" do
        bct_letter = BctLetter.create! valid_attributes
        put :update, {:id => bct_letter.to_param, :bct_letter => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested bct_letter" do
      bct_letter = BctLetter.create! valid_attributes
      expect {
        delete :destroy, {:id => bct_letter.to_param}, valid_session
      }.to change(BctLetter, :count).by(-1)
    end

    it "redirects to the bct_letters list" do
      bct_letter = BctLetter.create! valid_attributes
      delete :destroy, {:id => bct_letter.to_param}, valid_session
      expect(response).to redirect_to(bct_letters_url)
    end
  end

end
