require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DObjectsController do

  # This should return the minimal set of attributes required to create a valid
  # DObject. As you add validations to DObject, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {  }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DObjectsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all d_objects as @d_objects" do
      d_object = DObject.create! valid_attributes
      get :index, {}, valid_session
      assigns(:d_objects).should eq([d_object])
    end
  end

  describe "GET show" do
    it "assigns the requested d_object as @d_object" do
      d_object = DObject.create! valid_attributes
      get :show, {:id => d_object.to_param}, valid_session
      assigns(:d_object).should eq(d_object)
    end
  end

  describe "GET new" do
    it "assigns a new d_object as @d_object" do
      get :new, {}, valid_session
      assigns(:d_object).should be_a_new(DObject)
    end
  end

  describe "GET edit" do
    it "assigns the requested d_object as @d_object" do
      d_object = DObject.create! valid_attributes
      get :edit, {:id => d_object.to_param}, valid_session
      assigns(:d_object).should eq(d_object)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DObject" do
        expect {
          post :create, {:d_object => valid_attributes}, valid_session
        }.to change(DObject, :count).by(1)
      end

      it "assigns a newly created d_object as @d_object" do
        post :create, {:d_object => valid_attributes}, valid_session
        assigns(:d_object).should be_a(DObject)
        assigns(:d_object).should be_persisted
      end

      it "redirects to the created d_object" do
        post :create, {:d_object => valid_attributes}, valid_session
        response.should redirect_to(DObject.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved d_object as @d_object" do
        # Trigger the behavior that occurs when invalid params are submitted
        DObject.any_instance.stub(:save).and_return(false)
        post :create, {:d_object => {  }}, valid_session
        assigns(:d_object).should be_a_new(DObject)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DObject.any_instance.stub(:save).and_return(false)
        post :create, {:d_object => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested d_object" do
        d_object = DObject.create! valid_attributes
        # Assuming there are no other d_objects in the database, this
        # specifies that the DObject created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DObject.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => d_object.to_param, :d_object => { "these" => "params" }}, valid_session
      end

      it "assigns the requested d_object as @d_object" do
        d_object = DObject.create! valid_attributes
        put :update, {:id => d_object.to_param, :d_object => valid_attributes}, valid_session
        assigns(:d_object).should eq(d_object)
      end

      it "redirects to the d_object" do
        d_object = DObject.create! valid_attributes
        put :update, {:id => d_object.to_param, :d_object => valid_attributes}, valid_session
        response.should redirect_to(d_object)
      end
    end

    describe "with invalid params" do
      it "assigns the d_object as @d_object" do
        d_object = DObject.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DObject.any_instance.stub(:save).and_return(false)
        put :update, {:id => d_object.to_param, :d_object => {  }}, valid_session
        assigns(:d_object).should eq(d_object)
      end

      it "re-renders the 'edit' template" do
        d_object = DObject.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DObject.any_instance.stub(:save).and_return(false)
        put :update, {:id => d_object.to_param, :d_object => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested d_object" do
      d_object = DObject.create! valid_attributes
      expect {
        delete :destroy, {:id => d_object.to_param}, valid_session
      }.to change(DObject, :count).by(-1)
    end

    it "redirects to the d_objects list" do
      d_object = DObject.create! valid_attributes
      delete :destroy, {:id => d_object.to_param}, valid_session
      response.should redirect_to(d_objects_url)
    end
  end

end
