require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ExtraCardsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # ExtraCard. As you add validations to ExtraCard, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ExtraCardsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all extra_cards as @extra_cards" do
      extra_card = ExtraCard.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:extra_cards)).to eq([extra_card])
    end
  end

  describe "GET show" do
    it "assigns the requested extra_card as @extra_card" do
      extra_card = ExtraCard.create! valid_attributes
      get :show, {:id => extra_card.to_param}, valid_session
      expect(assigns(:extra_card)).to eq(extra_card)
    end
  end

  describe "GET new" do
    it "assigns a new extra_card as @extra_card" do
      get :new, {}, valid_session
      expect(assigns(:extra_card)).to be_a_new(ExtraCard)
    end
  end

  describe "GET edit" do
    it "assigns the requested extra_card as @extra_card" do
      extra_card = ExtraCard.create! valid_attributes
      get :edit, {:id => extra_card.to_param}, valid_session
      expect(assigns(:extra_card)).to eq(extra_card)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ExtraCard" do
        expect {
          post :create, {:extra_card => valid_attributes}, valid_session
        }.to change(ExtraCard, :count).by(1)
      end

      it "assigns a newly created extra_card as @extra_card" do
        post :create, {:extra_card => valid_attributes}, valid_session
        expect(assigns(:extra_card)).to be_a(ExtraCard)
        expect(assigns(:extra_card)).to be_persisted
      end

      it "redirects to the created extra_card" do
        post :create, {:extra_card => valid_attributes}, valid_session
        expect(response).to redirect_to(ExtraCard.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved extra_card as @extra_card" do
        post :create, {:extra_card => invalid_attributes}, valid_session
        expect(assigns(:extra_card)).to be_a_new(ExtraCard)
      end

      it "re-renders the 'new' template" do
        post :create, {:extra_card => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested extra_card" do
        extra_card = ExtraCard.create! valid_attributes
        put :update, {:id => extra_card.to_param, :extra_card => new_attributes}, valid_session
        extra_card.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested extra_card as @extra_card" do
        extra_card = ExtraCard.create! valid_attributes
        put :update, {:id => extra_card.to_param, :extra_card => valid_attributes}, valid_session
        expect(assigns(:extra_card)).to eq(extra_card)
      end

      it "redirects to the extra_card" do
        extra_card = ExtraCard.create! valid_attributes
        put :update, {:id => extra_card.to_param, :extra_card => valid_attributes}, valid_session
        expect(response).to redirect_to(extra_card)
      end
    end

    describe "with invalid params" do
      it "assigns the extra_card as @extra_card" do
        extra_card = ExtraCard.create! valid_attributes
        put :update, {:id => extra_card.to_param, :extra_card => invalid_attributes}, valid_session
        expect(assigns(:extra_card)).to eq(extra_card)
      end

      it "re-renders the 'edit' template" do
        extra_card = ExtraCard.create! valid_attributes
        put :update, {:id => extra_card.to_param, :extra_card => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested extra_card" do
      extra_card = ExtraCard.create! valid_attributes
      expect {
        delete :destroy, {:id => extra_card.to_param}, valid_session
      }.to change(ExtraCard, :count).by(-1)
    end

    it "redirects to the extra_cards list" do
      extra_card = ExtraCard.create! valid_attributes
      delete :destroy, {:id => extra_card.to_param}, valid_session
      expect(response).to redirect_to(extra_cards_url)
    end
  end

end
